Q-Learning
$$
Q^* (s,a)
$$
Optimal Policy
$$
\pi^*(s) = arg\max_a Q(s,a)
$$

### Main Equation
$$
Q(S_t,A_t) \leftarrow Q(S_t,A_t) + 
\alpha \Big[
R_{t+1} +
\gamma \max_a Q(S_{t+1},a)
-
Q(S_t,A_t)
\Big]
$$

- $$ Q(S_t,A_t): current estimate $$
- $$ R_t+1: reward $$
- $$ \gamma: discount factor $$
- $$ alpha: learning rate $$
- $$ max_a Q(S_{t+1},a): best future value $$

### TD Error

$$
\delta =
R_{t+1} +
\gamma \max_a Q(S_{t+1},a)
-
Q(S_t,A_t)
$$
Then update:
$$
Q \leftarrow Q + \alpha \delta
$$

In [0]:
import numpy as np
import random

In [0]:
states = [0,1,2]
actions = [0,1]

Q = np.zeros((3,2))

gamma = 0.9
alpha = 0.1
epsilon = 0.1

episodes = 1000

In [0]:
def step(state, action):
    if state == 0:
        if action == 0:
            return 0,0
        else:
            return 1,0
    
    if state == 1:
        if action == 0:
            return 0,0
        else:
            return 2,1
    
    return 2,0

In [0]:
for ep in range(episodes):
    state = 0
    while state != 2:

        #epsilon-greedy
        if random.random() < epsilon:
            action = random.choice(actions)
        else:
            action = np.argmax(Q[state])
        next_state, reward = step(state,action)
        Q[state,action] = Q[state,action] + action * (
            reward
            + gamma*np.max(Q[next_state])
            - Q[state,action] 
        )
        state = next_state

print("Q-table")
print(Q)

print("Optimal policy")
print(np.argmax(Q,axis=1))

Q-table
[[0.  0.9]
 [0.  1. ]
 [0.  0. ]]
Optimal policy
[1 1 0]


## Recommendation Environment Simulation (User Behavior)

In [0]:
states = [0,1,2]
actions = [0,1,2]

# Q table
Q = np.zeros((3,3))

alpha = 0.1
gamma = 0.9
epsilon = 0.1

episodes = 5000

In [0]:
def step(state, action):
    click_prob = [
        [0.8,0.3,0.2],
        [0.2,0.8,0.4],
        [0.2,0.4,0.8]
    ]
    prob = click_prob[state][action]
    reward = 1 if random.random() < prob else 0
    next_state = random.choice(states)
    return next_state, reward

In [0]:
for ep in range(episodes):

    state = random.choice(states)

    for t in range(10):

        # epsilon greedy
        if random.random() < epsilon:
            action = random.choice(actions)
        else:
            action = np.argmax(Q[state])

        next_state, reward = step(state, action)

        Q[state,action] += alpha*(
            reward +
            gamma*np.max(Q[next_state])
            - Q[state,action]
        )

        state = next_state

In [0]:
print("Q-table")
print(Q)

print("Optimal policy")
print(np.argmax(Q,axis=1))

Q-table
[[7.66065056 7.45862649 7.35999911]
 [7.26466964 7.79473484 7.50431941]
 [7.47093979 7.61729799 7.87663751]]
Optimal policy
[0 1 2]
