# RL in Basic Recommendation

## Problem Concept

สมมติ user มี 3 ประเภท
- state:0, user type: sports lover
- state:1, user type: movie lover
- state:2, user type: neutral

action = content ที่จะแนะนำ
- action:0, recommendation: sports content
- action:1, recommendation: movie content

reward
- result:user click, reward: +1
- result:user ignore, reward: 0

## MDP Definition

- State
$$
s \in \{0,1,2\}
$$

- Action
$$
a \in \{sports, movie\}
$$

- transition
$$
P(s'|s,a)
$$

- reward
$$
R(s,a)
$$

- discount factor
$$
\gamma
$$

## Bellman Optimality Equation

- Dynamic Programming
$$
V(s) =
\max_a
\sum_{s'} P(s'|s,a)
\left[
R(s,a) + \gamma V(s')
\right]
$$

## Environment Model

DP จำเป็นต้องกำหนด transition probability


In [1]:
P = {
    0:{ # sports user
        0:[(0.7,0,1),(0.3,2,0)],   # recommend sports
        1:[(0.4,1,1),(0.6,2,0)]    # recommend movie
    },
    1:{ # movie user
        0:[(0.4,0,1),(0.6,2,0)],
        1:[(0.7,1,1),(0.3,2,0)]
    },
    2:{ # neutral
        0:[(0.5,0,1),(0.5,2,0)],
        1:[(0.5,1,1),(0.5,2,0)]
    }
}

In [2]:
import numpy as np

In [3]:
states = [0,1,2]
actions = [0,1] # 0=sports, 1=movie

gamma = 0.9
theta = 1e-4

In [4]:
V = np.zeros(len(states))
V

array([0., 0., 0.])

In [5]:
while True:
    delta = 0
    
    for s in states:
        v = V[s]
        action_values = []
        
        for a in actions:
            value = 0
            
            for prob,next_state,reward in P[s][a]:
                value += prob * (reward + gamma*V[next_state])
            
            action_values.append(value)
        V[s] = max(action_values)
        delta = max(delta,abs(v-V[s]))
    if delta < theta:
        break

print("Optimal Value Function")
print(V)

Optimal Value Function
[6.34078387 6.34078387 6.09693438]


## Extract Recommendation Policy

In [6]:
policy = np.zeros(len(states))

for s in states:

    action_values = []

    for a in actions:

        value = 0

        for prob,next_state,reward in P[s][a]:

            value += prob * (reward + gamma*V[next_state])

        action_values.append(value)

    policy[s] = np.argmax(action_values)

print("Optimal Policy")
print(policy)

Optimal Policy
[0. 1. 0.]
